[server]
keystorePath = "./cert/certificate.pfx"
superserviceID = "_auto_generated_ID_" #default: ""
ssl = true #if use HTTPS
port = 3000 #default: 3000, port of server
numberOfProcess = 4 #default: 1
[cluster]
name = "owt-cluster"
[rabbit]
host = "217.22.213.14" #default: "localhost"
port = 5672 #default: 5672
[mongo]
dataBaseURL = "217.22.213.14/owtdb" #default: "localhost/owtdb"
